# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_collisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collision',
            name='total_time',
            field=models.FloatField(),
        ),
    ]
