# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170430_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='collision',
            name='firstTemp',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='collision',
            name='lastTemp',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
